# --- !Ups

CREATE TABLE IF NOT EXISTS SM_EXIF
(
  "ID"                   VARCHAR PRIMARY KEY NOT NULL,
  "DATE_TIME"            TIMESTAMP,
  "DATE_TIME_ORIGINAL"   TIMESTAMP,
  "DATE_TIME_DIGITIZED"  TIMESTAMP,
  "MAKE"                 VARCHAR,
  "MODEL"                VARCHAR,
  "SOFTWARE"             VARCHAR,
  "EXIF_IMAGE_WIDTH"     VARCHAR,
  "EXIF_IMAGE_HEIGHT"    VARCHAR
);



# --- !Downs

DROP TABLE IF EXISTS SM_EXIF CASCADE;

