# --- !Ups

CREATE TABLE IF NOT EXISTS SM_EXIF
(
    "ID"                    VARCHAR PRIMARY KEY NOT NULL,
    "DATE_TIME"             TIMESTAMP,
    "DATE_TIME_ORIGINAL"    TIMESTAMP,
    "DATE_TIME_DIGITIZED"   TIMESTAMP,
    "MAKE"                  VARCHAR,
    "MODEL"                 VARCHAR,
    "SOFTWARE"              VARCHAR,
    "EXIF_IMAGE_WIDTH"      VARCHAR,
    "EXIF_IMAGE_HEIGHT"     VARCHAR,
    "GPS_VERSION_ID"        VARCHAR,
    "GPS_LATITUDE_REF"      VARCHAR,
    "GPS_LATITUDE"          VARCHAR,
    "GPS_LONGITUDE_REF"     VARCHAR,
    "GPS_LONGITUDE"         VARCHAR,
    "GPS_ALTITUDE_REF"      VARCHAR,
    "GPS_ALTITUDE"          VARCHAR,
    "GPS_TIME_STAMP"        VARCHAR,
    "GPS_PROCESSING_METHOD" VARCHAR,
    "GPS_DATE_STAMP"        VARCHAR,
    "GPS_LATITUDE_DEC"      DECIMAL,
    "GPS_LONGITUDE_DEC"     DECIMAL
);



# --- !Downs

DROP TABLE IF EXISTS SM_EXIF CASCADE;

